{{- $root := . -}}
{{- range $name := list "bff" "api" "scanner" "promotion" "deletion" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-001-{{ $name }}
  labels:
    {{- include "sample-001.labels" $root | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: sample-001-{{ $name }}}
---
{{- end }}
