"""Internal shared free-text sanitization, label-charset, and content-hash
primitives.

Extracted from `gate_issues.py` (which originally defined these inline) so
`gate_issues_github.py` can reuse the same discipline without copy-pasting.
No public CLI surface of its own -- both call sites keep their own
domain-specific exception type (`gate_issues.GateIssuesError`,
`gate_issues_github.GateIssuesGithubError`) and simply catch
`ForgeTextError` and re-raise with the same message, so each call site keeps
its own exit-code mapping. Follows the exact `_forge_ledger.py` extraction
precedent (see that module's docstring) -- that module supplies shared
ledger/lock filesystem mechanics, this one supplies shared text mechanics.

This is a pure extraction: behavior, character sets, message text, and
length limits are unchanged from `gate_issues.py`'s original inline
implementation.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata

_LABEL_CHARSET_RE = re.compile(r"^[a-z0-9-]+$")
_MENTION_RE = re.compile(r"(?<!\w)@(\w[\w.-]*)")
_CROSS_REF_RE = re.compile(r"(?<!\w)([\w.-]+/[\w.-]+)?#(\d+)")
_FORBIDDEN_TEXT_CHARS = {"\x0b", "\x0c", "\x1c", "\x1d", "\x1e", "\x85", " ", " "}

_PROVENANCE_LINE = "> Machine-generated by agentic-sdlc."
_REF_LINE_PREFIX = "> ref "
_PARENT_LINE_PREFIX = "> parent "
_RESERVED_PREFIXES = (_PROVENANCE_LINE, _REF_LINE_PREFIX, _PARENT_LINE_PREFIX)


class ForgeTextError(ValueError):
    """Module-neutral sanitization failure. Callers catch this and re-raise
    their own domain-specific exception type (e.g. `gate_issues.GateIssuesError`,
    `gate_issues_github.GateIssuesGithubError`) with the same message -- see
    module docstring."""


def task_hash(task_id: str) -> str:
    return hashlib.sha256(task_id.encode("utf-8")).hexdigest()[:16]


# --------------------------------------------------------------------------
# Sanitization -- reject and abort, never substitute. Applied only to
# free-text fields sourced from authorities.json/run-record content
# (applicability_rationale, an authority requirement's rationale, and the
# optional --include-scope scope line); module-composed template text
# (banners, ref/parent lines) is never run through this.
# --------------------------------------------------------------------------


def _neutralize_references(text: str) -> str:
    zwsp = "​"

    def _mention(match: re.Match[str]) -> str:
        return "@" + zwsp + match.group(1)

    def _crossref(match: re.Match[str]) -> str:
        prefix = match.group(1) or ""
        return f"{prefix}#{zwsp}{match.group(2)}"

    text = _MENTION_RE.sub(_mention, text)
    text = _CROSS_REF_RE.sub(_crossref, text)
    return text


def sanitize_free_text(text: str, field_name: str) -> str:
    for ch in text:
        if ch in _FORBIDDEN_TEXT_CHARS:
            raise ForgeTextError(
                f"{field_name}: contains a forbidden control/line-separator character (U+{ord(ch):04X})"
            )
        if 0xD800 <= ord(ch) <= 0xDFFF:
            raise ForgeTextError(f"{field_name}: contains a lone Unicode surrogate")
    lines = text.splitlines()
    for line in lines:
        if line.strip().startswith("/"):
            raise ForgeTextError(
                f"{field_name}: contains a line starting with '/' (forge quick-action injection risk)"
            )
    for line in lines:
        if any(line.startswith(prefix) for prefix in _RESERVED_PREFIXES):
            raise ForgeTextError(f"{field_name}: contains a reserved provenance/ref/parent-line prefix")
    sanitized = _neutralize_references(text)
    if len(sanitized) > 4000:
        raise ForgeTextError(f"{field_name}: exceeds 4000 characters")
    return sanitized


def sanitize_title_text(text: str, field_name: str) -> str:
    normalized = unicodedata.normalize("NFKC", text)
    for ch in normalized:
        if not (0x20 <= ord(ch) <= 0x7E):
            raise ForgeTextError(f"{field_name}: contains a non-printable-ASCII character (U+{ord(ch):04X})")
    stripped = normalized.strip()
    if not stripped:
        raise ForgeTextError(f"{field_name}: empty after normalization/strip")
    if stripped[0] in ("-", "/"):
        raise ForgeTextError(f"{field_name}: must not start with '-' or '/'")
    if len(stripped) > 200:
        raise ForgeTextError(f"{field_name}: exceeds 200 characters")
    return stripped
