"""`create-requirement-issues` / `list-requirement-issues` (Stage A,
GitLab-only): back a G2 Requirements Baseline item list with real GitLab
issues, idempotently, with the forge itself (queried by label) as the
source of truth for "does this item already have an issue" -- never the
local ledger.

Deliberately backend-neutral: all policy logic (item loading/validation,
sanitization, marker/label helpers, body rendering, plan-digest
computation, ledger read/write, lock acquire/release, and the top-level
orchestration) lives here; only the actual GitLab calls live in
`gitlab_issue.py`. This module never imports `graph.py`, and `graph.py`
must never import this module or reference `requirement_issues`/
`requirement_ledger` by name -- this feature is never wired into graph
dispatch (see `test_graph_module_never_references_requirement_issues` in
`tests/test_requirement_issues_cli.py`).

Stage A: items come from an operator-supplied file, never from an agent.
No `AgentContribution`/`SUBMIT_CONTRIBUTION_SCHEMA` involvement.

Re-entry semantics: the same issue is *reused* for a given item across
re-entries (matched by its per-item label), never re-created as a new
"generation". No local "has this been created" bookkeeping is ever
trusted over a fresh label search against the forge.

## Accepted residual risk: quick-action verification gap (v1, human-input-only)

Post-creation verification (`_process_item`'s `failures` checks) can only
catch a quick-action injection if it corrupted a field this module
actually re-reads and compares: labels, assignees, confidential, state,
title, project, author. GitLab quick actions with no corresponding
checkable field on the issue resource -- e.g. `/relate`, `/spend`,
`/subscribe`, `/due`, `/weight`, `/milestone`, `/epic` -- are *not*
independently detectable by this verification step even though the
description-line quick-action rejection in `sanitize_description` (step 2)
is the actual, primary control against them ever reaching GitLab in the
first place. This residual gap (an unverifiable quick action slipping
through if the primary line-prefix rejection were ever itself bypassed) is
accepted for v1 specifically because Stage A only accepts human-supplied
input (see module docstring above) -- there is no agent/LLM content path
into this module today. This acceptance does **not** extend to any future
stage that lets agent-authored or otherwise less-trusted content reach
`create_gitlab_issue`; that stage must not be authorized without
revisiting this gap (e.g. broader quick-action detection, or verification
against a full issue-notes/system-notes audit trail rather than just the
issue resource's own fields).
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import socket
import sys
import tempfile
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from . import gitlab_issue
from .provider import fingerprint
from .runtime import _requirement_ledger_path, _requirement_lock_path

FIXED_LABEL = "agentic-sdlc"
LEDGER_SCHEMA_VERSION = 1
ITEMS_SCHEMA_VERSION = 1
DEFAULT_MAX_ITEMS = 50

_ITEM_KEY_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
_LABEL_CHARSET_RE = re.compile(r"^[a-z0-9-]+$")

# See §3.3 step 1: control/line-separator characters a naive Cc/Cf-category
# filter misses but `str.splitlines()` still treats as line breaks, closing
# the gap between "what splitlines() sees" and "what a naive split('\n')
# check sees" at the source, before either is used. This set is meant to be
# the *complete*, authoritative list of splitlines()-recognized line breaks
# (beyond plain \n/\r) -- \x85 (NEL) is included for that reason even though
# it is not independently exploitable today (the splitlines()-based
# quick-action-line check below also happens to catch it via a different
# path); do not remove entries just because another check happens to also
# cover them.
_FORBIDDEN_DESC_CHARS = {"\x0b", "\x0c", "\x1c", "\x1d", "\x1e", "\x85", "\u2028", "\u2029"}

_MENTION_RE = re.compile(r"(?<!\w)@(\w[\w.-]*)")
_CROSS_REF_RE = re.compile(r"(?<!\w)([\w.-]+/[\w.-]+)?#(\d+)")

_PROVENANCE_BANNER = (
    "> Machine-generated by agentic-sdlc. Not a human-authored requirement. Not approval evidence."
)
_REF_LINE_PREFIX = "> ref "


class RequirementIssuesError(ValueError):
    """Structural/policy failure -- CLI maps this to exit code 1."""


class RequirementIssuesBlocked(ValueError):
    """Needs human resolution (ambiguous match, drift, lock held, digest
    mismatch mid-run) -- CLI maps this to exit code 2."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# --------------------------------------------------------------------------
# Identity, markers, labels (spec §1)
# --------------------------------------------------------------------------


def compute_marker(task_id: str, gate_id: str, item_key: str) -> str:
    """Hashed identifier (never the raw `task_id`, which is operator-chosen
    and may be sensitive, and the target GitLab project may be more
    widely visible than the source repo)."""
    digest = hashlib.sha256(f"{task_id}\x00{gate_id}\x00{item_key}".encode("utf-8")).hexdigest()
    return digest[:16]


def item_label(marker: str) -> str:
    label = f"agentic-sdlc-item-{marker}"
    if not _LABEL_CHARSET_RE.fullmatch(label):
        raise RequirementIssuesError(f"computed label {label!r} violates the [a-z0-9-] label charset")
    return label


def task_hash(task_id: str) -> str:
    return hashlib.sha256(task_id.encode("utf-8")).hexdigest()[:16]


# --------------------------------------------------------------------------
# Item loading/validation (spec §2)
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Item:
    key: str
    title: str
    description: str
    content_hash: str  # fingerprint({"title": ..., "description": ...})


@dataclass(frozen=True)
class ItemsFile:
    schema_version: int
    gate_id: str
    items: list[Item]


def read_items_source(value: str) -> bytes:
    """Mirrors `cli.py`'s `_load_decision`: `value` is a file path, or
    `-` to read from stdin."""
    if value == "-":
        return sys.stdin.buffer.read()
    return Path(value).read_bytes()


def parse_items_file(raw: bytes, max_items: int) -> ItemsFile:
    try:
        payload = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RequirementIssuesError(f"--items is not valid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise RequirementIssuesError("--items must contain a JSON object")

    schema_version = payload.get("schema_version")
    if schema_version != ITEMS_SCHEMA_VERSION:
        raise RequirementIssuesError(
            f"--items schema_version must be {ITEMS_SCHEMA_VERSION}, got {schema_version!r}"
        )

    gate_id = payload.get("gate_id")
    if gate_id != "G2":
        raise RequirementIssuesError(f"--items gate_id must be 'G2' in v1, got {gate_id!r}")

    raw_items = payload.get("items")
    if not isinstance(raw_items, list) or not raw_items:
        raise RequirementIssuesError("--items must contain a non-empty 'items' array")
    if len(raw_items) > max_items:
        raise RequirementIssuesError(
            f"--items has {len(raw_items)} items, exceeding --max-items {max_items} -- "
            "refusing rather than truncating"
        )

    seen_keys: set[str] = set()
    items: list[Item] = []
    for entry in raw_items:
        if not isinstance(entry, dict):
            raise RequirementIssuesError("each item in --items must be a JSON object")
        key = entry.get("key")
        title = entry.get("title")
        description = entry.get("description")
        if not isinstance(key, str) or not _ITEM_KEY_RE.fullmatch(key):
            raise RequirementIssuesError(f"item key {key!r} does not match the required pattern")
        if key in seen_keys:
            raise RequirementIssuesError(f"duplicate item key {key!r} in --items")
        seen_keys.add(key)
        if not isinstance(title, str) or not isinstance(description, str):
            raise RequirementIssuesError(f"item {key!r} must have string 'title' and 'description' fields")
        content_hash = fingerprint({"title": title, "description": description})
        items.append(Item(key=key, title=title, description=description, content_hash=content_hash))

    return ItemsFile(schema_version=schema_version, gate_id=gate_id, items=items)


# --------------------------------------------------------------------------
# Sanitization (spec §3.2, §3.3) -- reject and abort, never substitute.
# Deliberately NOT `agents._sanitized_artifact_field`, which substitutes a
# default on failure -- wrong here, since that would still create an
# externally-visible issue with a placeholder title.
# --------------------------------------------------------------------------


def sanitize_title(title: str, item_key: str) -> str:
    normalized = unicodedata.normalize("NFKC", title)
    for ch in normalized:
        if not (0x20 <= ord(ch) <= 0x7E):
            raise RequirementIssuesError(
                f"item {item_key!r}: title contains a non-printable-ASCII character (U+{ord(ch):04X})"
            )
    stripped = normalized.strip()
    if not stripped:
        raise RequirementIssuesError(f"item {item_key!r}: title is empty after normalization/strip")
    if stripped[0] in ("-", "/"):
        raise RequirementIssuesError(f"item {item_key!r}: title must not start with '-' or '/'")
    if len(stripped) > 200:
        raise RequirementIssuesError(f"item {item_key!r}: title exceeds 200 characters")
    return stripped


def _has_lone_surrogate(text: str) -> bool:
    return any(0xD800 <= ord(ch) <= 0xDFFF for ch in text)


def _neutralize_references(text: str) -> str:
    """Neutralize `@mentions` and `owner/repo#N` / bare `#N` cross-refs by
    inserting a zero-width space (U+200B) so GitLab's autolinking never
    fires, while keeping the description human-readable. One approach,
    applied consistently to both mention and cross-ref forms."""

    zwsp = "\u200b"

    def _mention(match: re.Match[str]) -> str:
        return "@" + zwsp + match.group(1)

    def _crossref(match: re.Match[str]) -> str:
        prefix = match.group(1) or ""
        return f"{prefix}#{zwsp}{match.group(2)}"

    text = _MENTION_RE.sub(_mention, text)
    text = _CROSS_REF_RE.sub(_crossref, text)
    return text


def sanitize_description(description: str, item_key: str) -> str:
    # 1. Reject forbidden control/line-separator characters and lone
    # surrogates outright -- this is what makes `splitlines()` and a naive
    # `split("\n")` agree, closing the bypass at the source (see module
    # docstring / `_FORBIDDEN_DESC_CHARS`).
    for ch in description:
        if ch in _FORBIDDEN_DESC_CHARS:
            raise RequirementIssuesError(
                f"item {item_key!r}: description contains a forbidden control/line-separator "
                f"character (U+{ord(ch):04X})"
            )
    if _has_lone_surrogate(description):
        raise RequirementIssuesError(f"item {item_key!r}: description contains a lone Unicode surrogate")

    # 2. Reject GitLab quick-action injection: any line whose stripped
    # form starts with "/" (e.g. "/assign @victim", "/confidential").
    lines = description.splitlines()
    for line in lines:
        if line.strip().startswith("/"):
            raise RequirementIssuesError(
                f"item {item_key!r}: description contains a line starting with '/' "
                "(GitLab quick-action injection risk)"
            )

    # 3. Reject the reserved provenance-banner/ref-line prefixes anywhere
    # in operator-supplied content -- only this module ever emits them.
    for line in lines:
        if line.startswith(_REF_LINE_PREFIX) or line.startswith(_PROVENANCE_BANNER):
            raise RequirementIssuesError(
                f"item {item_key!r}: description contains the reserved provenance/ref-line prefix"
            )

    # 4. Neutralize @mentions and cross-references.
    sanitized = _neutralize_references(description)

    # 5. Length cap, checked after neutralization (which can only grow the
    # string, never shrink it below the raw length).
    if len(sanitized) > 8000:
        raise RequirementIssuesError(f"item {item_key!r}: description exceeds 8000 characters")

    return sanitized


def _fence_length(text: str) -> int:
    longest = 0
    current = 0
    for ch in text:
        if ch == "`":
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    return max(3, longest + 1)


def render_body(task_id: str, gate_id: str, marker: str, sanitized_description: str) -> str:
    """Spec §4 body template. `<task-hash>` is `sha256(task_id)[:16]` --
    never the raw task_id. The `ref` line is a human-readable hint only;
    the *label* (see `item_label`) is the actual trust anchor -- nothing
    here or in `requirement_issues.py`'s existence check ever searches on
    this line's text."""
    fence = "`" * _fence_length(sanitized_description)
    return (
        f"{_PROVENANCE_BANNER}\n"
        f"{_REF_LINE_PREFIX}{task_hash(task_id)}/{gate_id}/{marker}\n"
        "\n"
        f"{fence}\n"
        f"{sanitized_description}\n"
        f"{fence}\n"
    )


@dataclass(frozen=True)
class SanitizedItem:
    key: str
    raw_title: str
    raw_description: str
    title: str
    body: str
    marker: str
    label: str
    content_hash: str


def sanitize_items(task_id: str, gate_id: str, items: list[Item]) -> list[SanitizedItem]:
    """Sanitize every item up front, both dry-run and apply. A rejected
    title/description aborts the whole run before any GitLab call is
    made, naming the offending item key -- never a partial run, never a
    substituted placeholder."""
    result = []
    for item in items:
        marker = compute_marker(task_id, gate_id, item.key)
        label = item_label(marker)
        title = sanitize_title(item.title, item.key)
        description = sanitize_description(item.description, item.key)
        body = render_body(task_id, gate_id, marker, description)
        result.append(
            SanitizedItem(
                key=item.key,
                raw_title=item.title,
                raw_description=item.description,
                title=title,
                body=body,
                marker=marker,
                label=label,
                content_hash=item.content_hash,
            )
        )
    return result


# --------------------------------------------------------------------------
# Plan digest (spec §3.1)
# --------------------------------------------------------------------------


def compute_plan_digest(
    *,
    task_id: str,
    gate_id: str,
    project: str,
    items_raw: bytes,
    item_keys: list[str],
    item_hashes: dict[str, str],
    run_halted: bool,
    required_reentry_gate: str | None,
    gate_status: str | None,
    re_entry_count: int,
) -> str:
    payload = {
        "task_id": task_id,
        "gate_id": gate_id,
        "project": project,
        "items_digest": "sha256:" + hashlib.sha256(items_raw).hexdigest(),
        "item_keys": list(item_keys),
        "item_hashes": dict(item_hashes),
        "eligibility": {
            "run_halted": run_halted,
            "required_reentry_gate": required_reentry_gate,
            "publishable": gate_status not in {"blocked", "invalidated"},
            "re_entry_count": re_entry_count,
        },
    }
    return fingerprint(payload)


def check_publish_eligibility(
    *, run_halted: bool, required_reentry_gate: str | None, gate_status: str | None
) -> None:
    if run_halted:
        raise RequirementIssuesBlocked(
            "task run is halted (mutation-gate rejection) -- cannot publish requirement issues"
        )
    if required_reentry_gate:
        raise RequirementIssuesBlocked(
            f"gate has a pending required_reentry_gate={required_reentry_gate!r} -- resolve reentry first"
        )
    if gate_status in {"blocked", "invalidated"}:
        raise RequirementIssuesBlocked(f"gate status {gate_status!r} is not publish-eligible")


# --------------------------------------------------------------------------
# Sidecar ledger (spec §2, §3.7)
# --------------------------------------------------------------------------


def _empty_ledger(task_id: str) -> dict[str, Any]:
    return {
        "schema_version": LEDGER_SCHEMA_VERSION,
        "task_id": task_id,
        "gate_id": None,
        "project": None,
        "bot_username": None,
        "mocked": False,
        "entries": {},
    }


def read_ledger(root: Path, task_id: str) -> dict[str, Any]:
    path = _requirement_ledger_path(Path(root), task_id)
    if not path.is_file():
        return _empty_ledger(task_id)
    return json.loads(path.read_text(encoding="utf-8"))


def write_ledger(root: Path, task_id: str, ledger: dict[str, Any]) -> None:
    """Exact durable-write sequence from spec §3.7: full-file rewrite,
    same-filesystem tmp file, fsync data, atomic rename, fsync the
    containing directory so the rename itself survives power loss."""
    path = _requirement_ledger_path(Path(root), task_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = (json.dumps(ledger, indent=2, sort_keys=True) + "\n").encode("utf-8")

    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=".requirement-issues.", suffix=".tmp")
    try:
        os.write(fd, payload)
        os.fsync(fd)
    finally:
        os.close(fd)
    os.chmod(tmp_name, 0o600)
    os.replace(tmp_name, path)

    dir_fd = os.open(str(path.parent), os.O_DIRECTORY)
    try:
        os.fsync(dir_fd)
    finally:
        os.close(dir_fd)


# --------------------------------------------------------------------------
# Whole-run lock (spec §3.0 step 6)
# --------------------------------------------------------------------------


def acquire_lock(root: Path, task_id: str, *, break_lock: bool) -> Path:
    path = _requirement_lock_path(Path(root), task_id)
    path.parent.mkdir(parents=True, exist_ok=True)

    if break_lock and path.is_file():
        path.unlink(missing_ok=True)

    try:
        fd = os.open(str(path), os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError:
        holder = "(unreadable)"
        try:
            holder = path.read_text(encoding="utf-8")
        except OSError:
            pass
        raise RequirementIssuesBlocked(
            f"requirement-issues.lock is already held -- pass --break-lock to override "
            f"(never auto-broken on timeout). Holder:\n{holder}"
        ) from None

    payload = json.dumps(
        {"pid": os.getpid(), "host": socket.gethostname(), "started_at": _now()}, indent=2
    )
    os.write(fd, payload.encode("utf-8"))
    os.close(fd)
    return path


def release_lock(path: Path) -> None:
    try:
        path.unlink()
    except FileNotFoundError:
        pass


# --------------------------------------------------------------------------
# Per-item existence check / create+verify / drift report (spec §3.4-3.6)
# --------------------------------------------------------------------------


def _validate_matched_issue(issue: dict[str, Any], si: SanitizedItem, item_key: str) -> None:
    """Validate a *reused* (already-existing) matched issue's labels.

    Deliberately containment, not exact-set-equality, unlike the
    post-creation verification in `_process_item` (which *does* require
    `set(labels) == {FIXED_LABEL, ITEM_LABEL}` exactly, since it is
    checking an issue this run itself just created and nothing else
    should have touched it yet). A long-lived *reused* issue may
    legitimately accumulate other labels over its life (triage, priority,
    team, ...) between re-entries -- requiring exact-set-equality here
    would break normal reuse for any issue a human has ever additionally
    labeled. What must still hold, and is still checked exactly, is that
    the two anchor labels (`FIXED_LABEL`, this item's own `ITEM_LABEL`)
    are both present and that no *other* `agentic-sdlc-item-*` label is
    present (which would indicate a mismatched/poisoned issue, not benign
    accumulated labeling).
    """
    labels = set(issue.get("labels") or [])
    if FIXED_LABEL not in labels:
        raise RequirementIssuesBlocked(
            f"item {item_key!r}: matched issue is missing the {FIXED_LABEL!r} anchor label"
        )
    if si.label not in labels:
        raise RequirementIssuesBlocked(
            f"item {item_key!r}: matched issue is missing its own item label {si.label!r}"
        )
    foreign = {l for l in labels if l.startswith("agentic-sdlc-item-") and l != si.label}
    if foreign:
        raise RequirementIssuesBlocked(
            f"item {item_key!r}: matched issue carries a foreign item label {sorted(foreign)} "
            "-- possible mismatch/poisoned issue"
        )


def _process_item(
    root: Path, task_id: str, project: str, si: SanitizedItem, ledger: dict[str, Any], *,
    mocked: bool, bot_username: str,
) -> dict[str, Any]:
    try:
        return _process_item_inner(root, task_id, project, si, ledger, mocked=mocked, bot_username=bot_username)
    except (RequirementIssuesError, RequirementIssuesBlocked):
        raise
    except ValueError as exc:
        # Plain `ValueError` from `gitlab_issue.py` (a failed `glab`
        # call, malformed response, ...) is a structural failure, not a
        # human-resolvable ambiguity -- map it to exit code 1, not 2.
        raise RequirementIssuesError(f"item {si.key!r}: {exc}") from exc


def _process_item_inner(
    root: Path, task_id: str, project: str, si: SanitizedItem, ledger: dict[str, Any], *,
    mocked: bool, bot_username: str,
) -> dict[str, Any]:
    prior_entry = ledger["entries"].get(si.key)

    existing = gitlab_issue.search_gitlab_issues_by_labels(project, [FIXED_LABEL, si.label])
    if len(existing) > 1:
        raise RequirementIssuesBlocked(
            f"item {si.key!r}: {len(existing)} issues matched labels "
            f"[{FIXED_LABEL}, {si.label}] -- ambiguous identity, needs human resolution"
        )

    if len(existing) == 1:
        issue = existing[0]
        _validate_matched_issue(issue, si, si.key)
        iid = issue.get("iid")
        uri = gitlab_issue.gitlab_issue_uri(project, iid)

        # Author check on reuse, mirroring the create path's
        # post-creation verification. The item label is deterministic
        # and not secret (see `compute_marker`'s docstring -- hashing is
        # to avoid leaking `task_id` externally, not to make the label
        # unguessable), so without this check any Reporter+ contributor
        # to the target project could pre-create an issue carrying
        # `[FIXED_LABEL, item_label]` and have this tool silently adopt
        # it as canonical -- worse than the accepted quick-action gap,
        # since none of the creation-time controls (sanitization,
        # post-creation verification) ever ran against that content at
        # all. A follow-up authoritative fetch (not just the search
        # response, whose exact field set isn't guaranteed here) is used
        # so `author_username`/`state` are both read from the same
        # verification shape the create path already trusts.
        verification = gitlab_issue.fetch_gitlab_issue_verification(project, iid)
        verified_author = (verification.get("author_username") or "").lower()
        if verified_author != bot_username.lower():
            entry = {
                "item_key": si.key,
                "marker": si.marker,
                "status": "suspect",
                "issue_uri": uri,
                "issue_state": verification.get("state"),
                "content_hash": si.content_hash,
                "prior_title": si.raw_title,
                "prior_description": si.raw_description,
                "attempted_at": _now(),
                "recorded_at": _now(),
                "detail": (
                    f"matched issue author {verification.get('author_username')!r} does not match "
                    f"the verified bot identity {bot_username!r} -- refusing to reuse a "
                    "possibly attacker-created issue"
                ),
            }
            ledger["entries"][si.key] = entry
            ledger["mocked"] = mocked
            write_ledger(root, task_id, ledger)
            raise RequirementIssuesBlocked(
                f"item {si.key!r}: matched issue's author does not match the verified bot identity "
                "-- refusing to reuse, needs human resolution"
            )

        state = verification.get("state")

        if prior_entry is None:
            drift = "reused (drift-unknown)"
        elif prior_entry.get("content_hash") != si.content_hash:
            drift = "changed_content"
        else:
            drift = None
        if state == "closed":
            drift = "reused (closed)" if drift is None else f"{drift}; reused (closed)"

        entry = {
            "item_key": si.key,
            "marker": si.marker,
            "status": "reused",
            "issue_uri": uri,
            "issue_state": state,
            "content_hash": si.content_hash,
            "prior_title": si.raw_title,
            "prior_description": si.raw_description,
            "attempted_at": _now(),
            "recorded_at": _now(),
            "detail": drift,
        }
        ledger["entries"][si.key] = entry
        ledger["mocked"] = mocked
        write_ledger(root, task_id, ledger)
        return {
            "item_key": si.key,
            "status": "reused",
            "issue_uri": uri,
            "issue_state": state,
            "drift": drift,
            "previous_title": prior_entry.get("prior_title") if prior_entry else None,
            "previous_description": prior_entry.get("prior_description") if prior_entry else None,
        }

    # --- create path (spec §3.5) -----------------------------------------
    entry = {
        "item_key": si.key,
        "marker": si.marker,
        "status": "creating",
        "issue_uri": None,
        "issue_state": None,
        "content_hash": si.content_hash,
        "prior_title": si.raw_title,
        "prior_description": si.raw_description,
        "attempted_at": _now(),
        "recorded_at": None,
        "detail": None,
    }
    ledger["entries"][si.key] = entry
    ledger["mocked"] = mocked
    write_ledger(root, task_id, ledger)  # BEFORE the API call, per spec.

    iid = gitlab_issue.create_gitlab_issue(project, si.title, si.body, [FIXED_LABEL, si.label])
    uri = gitlab_issue.gitlab_issue_uri(project, iid)
    verification = gitlab_issue.fetch_gitlab_issue_verification(project, iid)

    failures: list[str] = []
    if verification.get("title") != si.title:
        failures.append("title")
    if verification.get("state") != "opened":
        failures.append("state")
    if set(verification.get("labels") or []) != {FIXED_LABEL, si.label}:
        failures.append("labels")
    if verification.get("assignee_count", 0) != 0:
        failures.append("assignee_count")
    if verification.get("confidential", False) is not False:
        failures.append("confidential")
    if verification.get("project_path") != project:
        failures.append("project_path")
    verified_author = verification.get("author_username") or ""
    if verified_author.lower() != bot_username.lower():
        failures.append("author_username")

    if failures:
        entry = dict(entry)
        entry["status"] = "suspect"
        entry["issue_uri"] = uri
        entry["issue_state"] = verification.get("state")
        entry["recorded_at"] = _now()
        entry["detail"] = f"post-creation verification failed: {', '.join(failures)}"
        ledger["entries"][si.key] = entry
        write_ledger(root, task_id, ledger)
        raise RequirementIssuesBlocked(
            f"item {si.key!r}: post-creation verification failed ({', '.join(failures)}) "
            "-- aborting the entire run immediately"
        )

    entry = dict(entry)
    entry["status"] = "created"
    entry["issue_uri"] = uri
    entry["issue_state"] = verification.get("state")
    entry["recorded_at"] = _now()
    ledger["entries"][si.key] = entry
    write_ledger(root, task_id, ledger)
    return {"item_key": si.key, "status": "created", "issue_uri": uri, "issue_state": verification.get("state"), "drift": None}


# --------------------------------------------------------------------------
# Top-level orchestration (spec §3.0-§3.7)
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Eligibility:
    run_halted: bool
    required_reentry_gate: str | None
    gate_status: str | None
    re_entry_count: int
    classification: str | None


def run(
    *,
    root: Path,
    task_id: str,
    project: str,
    items_source: str,
    as_bot: str,
    apply: bool,
    plan_digest: str | None,
    allow_classification: str | None,
    max_items: int,
    break_lock: bool,
    i_know_this_is_mocked: bool,
    get_eligibility: Callable[[], Eligibility],
) -> dict[str, Any]:
    """Orchestrate `create-requirement-issues`, dry-run or apply.

    `get_eligibility` is a caller-supplied callback (see `cli.py`) that
    fetches live `run_halted`/`required_reentry_gate`/gate `status`/
    `re_entry_history` length/`classification` from the compiled graph's
    checkpointed state -- this module never imports `graph.py`/`runtime`'s
    graph-building machinery itself, keeping it backend-neutral and
    unreachable from `graph.py`'s dispatch (see module docstring).
    Re-invoked before every item in apply mode so a concurrent
    `reenter`/`invalidate` mid-loop is caught at the next item boundary.

    Raises `RequirementIssuesError` (CLI exit 1) or
    `RequirementIssuesBlocked` (CLI exit 2) on any preflight/sanitization/
    verification failure.
    """
    root = Path(root)
    try:
        raw = read_items_source(items_source)
    except OSError as exc:
        # A nonexistent/unreadable --items file (FileNotFoundError,
        # PermissionError, IsADirectoryError, ...) must abort cleanly
        # the same way a malformed-JSON --items file already does
        # (`parse_items_file` below), not surface as a raw traceback.
        raise RequirementIssuesError(f"unable to read --items {items_source!r}: {exc}") from exc
    items_file = parse_items_file(raw, max_items)
    gate_id = items_file.gate_id

    sanitized_items = sanitize_items(task_id, gate_id, items_file.items)
    item_keys = [i.key for i in items_file.items]
    item_hashes = {i.key: i.content_hash for i in items_file.items}

    def _digest_for(eligibility: Eligibility) -> str:
        return compute_plan_digest(
            task_id=task_id,
            gate_id=gate_id,
            project=project,
            items_raw=raw,
            item_keys=item_keys,
            item_hashes=item_hashes,
            run_halted=eligibility.run_halted,
            required_reentry_gate=eligibility.required_reentry_gate,
            gate_status=eligibility.gate_status,
            re_entry_count=eligibility.re_entry_count,
        )

    eligibility = get_eligibility()
    digest = _digest_for(eligibility)

    if allow_classification is None or allow_classification != eligibility.classification:
        raise RequirementIssuesError(
            "--allow-classification must be supplied and exactly match the task's classification "
            f"(got {allow_classification!r}, task classification is {eligibility.classification!r})"
        )

    check_publish_eligibility(
        run_halted=eligibility.run_halted,
        required_reentry_gate=eligibility.required_reentry_gate,
        gate_status=eligibility.gate_status,
    )

    mocked = bool(os.environ.get(gitlab_issue.ISSUE_CREATE_MOCK_ENV_VAR))

    if not apply:
        return {
            "mode": "dry-run",
            "plan_digest": digest,
            "gate_id": gate_id,
            "project": project,
            "mocked": mocked,
            "items": [
                {
                    "item_key": si.key,
                    "marker": si.marker,
                    "label": si.label,
                    "content_hash": si.content_hash,
                }
                for si in sanitized_items
            ],
        }

    if plan_digest is None:
        raise RequirementIssuesError("--apply requires --plan-digest (from a prior --dry-run)")
    if plan_digest != digest:
        raise RequirementIssuesBlocked(
            f"--plan-digest mismatch: recomputed {digest!r} != supplied {plan_digest!r} "
            "-- state changed since the --dry-run this digest came from; re-run --dry-run"
        )

    if mocked and not i_know_this_is_mocked:
        raise RequirementIssuesError(
            f"{gitlab_issue.ISSUE_CREATE_MOCK_ENV_VAR} is set but --i-know-this-is-mocked was not "
            "passed -- refusing to --apply against a mocked GitLab backend"
        )

    try:
        verified_username = gitlab_issue.verify_gitlab_identity(as_bot)
    except ValueError as exc:
        raise RequirementIssuesError(str(exc)) from exc

    lock_path = acquire_lock(root, task_id, break_lock=break_lock)
    try:
        ledger = read_ledger(root, task_id)
        ledger["schema_version"] = LEDGER_SCHEMA_VERSION
        ledger["task_id"] = task_id
        ledger["gate_id"] = gate_id
        ledger["project"] = project
        ledger["bot_username"] = verified_username
        ledger["mocked"] = mocked
        ledger.setdefault("entries", {})

        results = []
        for si in sanitized_items:
            fresh_digest = _digest_for(get_eligibility())
            if fresh_digest != plan_digest:
                raise RequirementIssuesBlocked(
                    f"plan digest changed before item {si.key!r} (a reenter/invalidate happened "
                    "concurrently) -- aborting remaining items; already-created issues are unaffected"
                )
            result = _process_item(
                root, task_id, project, si, ledger, mocked=mocked, bot_username=verified_username
            )
            results.append(result)

        return {
            "mode": "apply",
            "plan_digest": digest,
            "gate_id": gate_id,
            "project": project,
            "mocked": mocked,
            "bot_username": verified_username,
            "results": results,
        }
    finally:
        release_lock(lock_path)
